### ISSUE TITLE
Milestone 10 release and report

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#250]
- [ ] July release to include new data from WA, QLD

- [ ] financial report

- [ ] application and hosting report 

- [ ] ARENA template report
