### ISSUE TITLE
AREMI - June 2019 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#353]
- [x] another update to latest terriajs: to include feedback bug fix

- [x]  update to latest TerriaJS: to check if included: story, share from catalogue group 

- [x] ISF new regions PR ready: https://github.com/TerriaJS/aremi-natmap/pull/331 - @meh9 

- [x] ISF NOM new data https://github.com/TerriaJS/aremi-natmap/issues/320 - @meh9 

- [x] ISF Solar PV potential: https://github.com/TerriaJS/aremi-natmap/issues/352 - @KeyboardSounds 

- [x] treat 404 error Terriajs/terriajs#3453

**Comment by meh9** [comment]
Done!
