### ISSUE TITLE
AREMI - August 2019 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#382]
- [x] QUT analytics https://github.com/TerriaJS/cesium/pull/49; https://github.com/TerriaJS/terriajs/pull/3609#discussion_r307593537

- [x] check boxes for analytics: https://github.com/TerriaJS/terriajs/pull/3135

- [ ] Pumped hydro data update: https://github.com/TerriaJS/aremi-natmap/issues/384 - to be done outside a code release 

- [x] NSW data update - https://github.com/TerriaJS/aremi-natmap/issues/376; PR here: https://github.com/TerriaJS/aremi-natmap/pull/381

- [x] terriajs update, especially to include this: https://github.com/TerriaJS/aremi-natmap/pull/379; code release prepared here: https://github.com/TerriaJS/aremi-natmap/pull/383

- [x] update to latest terria server 3.0.1 which fixes bug with shortening url when sharing TerriaJS/terriajs#3510; code release prepared here: https://github.com/TerriaJS/aremi-natmap/pull/383

- [x] update satellite imagery catalogue: https://github.com/TerriaJS/aremi-natmap/issues/386

**Comment by Jason-DNetto** [comment]
![image](https://user-images.githubusercontent.com/24259173/62103398-bc699d00-b2df-11e9-9637-9420e5026cd1.png)
can this also include https://github.com/TerriaJS/terriajs/pull/3135 checkbox_groups

**Comment by AnaBelgun** [comment]
Code release done
