### ISSUE TITLE
AREMI - 28 May 2020 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#410]
- [x] NSW name changes - https://github.com/TerriaJS/aremi-natmap/issues/406
- [x] LGA 2019 - https://github.com/TerriaJS/aremi-natmap/issues/388 https://geo.abs.gov.au/arcgis/rest/services/ASGS2019/LGA/MapServer
- [x] update National Piggery layers https://github.com/TerriaJS/aremi-natmap/issues/413

- [x] add CLUM 2019 - https://github.com/TerriaJS/aremi-natmap/issues/414

- [x] ABBA contact details to be updated - https://github.com/TerriaJS/aremi-natmap/issues/417 

- [x] ABBA WA - reorg of some catalogue groups: https://github.com/TerriaJS/aremi-natmap/issues/418

- [x] Hotspots data https://github.com/TerriaJS/aremi-natmap/issues/419

**Post release item (TBC)**---------------------------------------------------------------------------------

- [ ] Analytics integration - pending QUT re-activating the service (transferring from NECTAR to Google Cloud) 
- https://github.com/TerriaJS/aremi-natmap/issues/389
- Fetch xhr https://github.com/TerriaJS/cesium/pull/49
- https://github.com/TerriaJS/terriajs/pull/3609#discussion_r307593537
- checkboxes https://github.com/TerriaJS/terriajs/pull/3135

![image](https://user-images.githubusercontent.com/18452161/81526122-1ed8e900-939a-11ea-8890-7925a4483ac7.png)

**Comment by AnaBelgun** [comment]
released by Nanda on 1/06/20.
