### ISSUE TITLE
AREMI - Aug 2020 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#425]
- [x] EV Map layers 

- [x] new population density layers https://github.com/TerriaJS/aremi-natmap/issues/426 

- [x] new Australian Topography basemap layer: https://github.com/TerriaJS/aremi-natmap/issues/427 

- [x] Update TerriaJS to include WPS fix https://github.com/TerriaJS/terriajs/pull/4331

- [x] Western Power electricity data prompts users for login https://github.com/TerriaJS/aremi-natmap/issues/429

- [x] NoM update: https://github.com/TerriaJS/aremi-natmap/issues/431

----------------------------------------------------------------------------------------------------------------------------------------------
**Post Aug 2020 release**

- [ ] ABBA analytics integration  - https://github.com/TerriaJS/aremi-natmap/issues/424 
NOTE: once in AREMI, send prototype url to ABBA team to test analytics before sending to GA

**Comment by AnaBelgun** [comment]
Hi @rowanwins we will need to wait with this release until the NoM data is in https://github.com/TerriaJS/aremi-natmap/issues/431
unless we do a release just for the EV layers and another one for analytics and NoM - mid Sep 2020

**Comment by AnaBelgun** [comment]
Testing of the ABBA analytics revealed a lot of issues with: 
- performance (takes a very long time to load, almost un-usable)
- although all checkboxes were selected, results did not appear even for small radius (less than 30km)

Due to these issues, we'll proceed with the release without analytics and re-release a new version when it's ready. 

Thanks Ana
Don’t hold up your other updates for this. Not sure how long it will take us to sort through.
Cheers
